# Generated by Django 4.2.1 on 2023-06-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=150)),
                ('license_plate', models.CharField(max_length=100)),
                ('car_brand', models.CharField(max_length=100)),
                ('car_year', models.IntegerField(max_length=10)),
                ('car_color', models.CharField(max_length=100)),
                ('RENAVAM', models.IntegerField(max_length=9)),
            ],
        ),
    ]
