# Generated by Django 4.2.1 on 2023-06-16 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_carros_ano_do_carro_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carros',
            new_name='Cars',
        ),
    ]
