# Generated by Django 4.2.1 on 2023-06-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome_do_usuário_do_veículo', models.CharField(max_length=150)),
                ('Placa_do_Carro', models.CharField(max_length=100)),
                ('Marca_do_Carro', models.CharField(max_length=100)),
                ('Ano_do_Carro', models.IntegerField(max_length=10)),
                ('Cor_do_veiculo', models.CharField(max_length=100)),
                ('Número_do_RENAVAM', models.IntegerField(max_length=9)),
            ],
        ),
    ]
